package com.dingtalk.sdk.entity;

/**
 * 钉钉接口全局返回码枚举<br>
 * @author henrybit
 * @since 1.0
 * @version 1.0
 */
public enum ResultType {

    SYS_BUSY(-1,"系统繁忙"),
    SUCCESS(0,"请求成功"),
    URL_NO_FOUND(404,"请求的URI地址不存在"),
    ILLEGAL_COR_ID(33001,"无效的企业ID"),
    ILLEGAL_APP_NAME(33002,"无效的微应用的名称"),
    ILLEGAL_APP_DESC(33003,"无效的微应用的描述"),
    ILLEGAL_APP_ICON(33004,"无效的微应用的ICON"),
    ILLEGAL_APP_INDEX(33005,"无效的微应用的移动端主页"),
    ILLEGAL_PC_INDEX(33006,"无效的微应用的PC端主页"),
    APP_PC_DIFF(33007,"微应用的移动端的主页与PC端主页不同"),
    ILLEGAL_OA_INDEX(33008,"无效的微应用OA后台的主页"),
    ILLEGAL_SESSION_ID(34001,"无效的会话id"),
    ILLEGAL_SESSION_SENDER(34002,"无效的会话消息的发送者"),
    ILLEGAL_SESSION_COR_ID(34003,"无效的会话消息的发送者的企业Id"),
    ILLEGAL_SESSION_TYPE(34004,"无效的会话消息的类型"),
    ILLEGAL_SESSION_VIDEO_PLAY_TIME(34005,"无效的会话音频消息的播放时间"),
    ILLEGAL_SENDER_NOT_IN_COR(34006,"发送者不在企业中"),
    SENDER_NOT_IN_SESSION(34007,"发送者不在会话中"),
    IMG_NOT_NULL(34008,"图片不能为空"),
    LINK_NOT_NULL(34009,"链接内容不能为空"),
    FILE_NOT_NULL(34010,"文件不能为空"),
    VIDEO_NOT_NULL(34011,"音频文件不能为空"),
    SEND_COR_NOT_FOUND(34012,"找不到发送者的企业"),
    SESSION_NOT_FOUND(34013,"找不到群会话对象"),
    ILLEGAL_SESSION_JSON(34014,"会话消息的json结构无效或不完整"),
    TOKEN_SECRET_OR_ACCESSTOKEN_ERROR(40001,"获取access_token时Secret错误，或者access_token无效"),
    TOKEN_INVALID(40002,"不合法的凭证类型"),
    USERID_INVALID(40003,"不合法的UserID"),
    MEDIA_FILE_INVALID(40004,"不合法的媒体文件类型"),
    INVALID_FILE_TYPE(40005,"不合法的文件类型"),
    INVALID_FILE_SIZE(40006,"不合法的文件大小"),
    INVALID_MEDIA_ID(40007,"不合法的媒体文件id"),
    INVALID_MSG_TYPE(40008,"不合法的消息类型"),
    INVALID_COR_ID(40009,"不合法的部门id"),
    INVALID_PARENT_COR_ID(40010,"不合法的父部门id"),
    INVALID_ORDER(40011,"不合法的排序order"),
    INVALID_SENDER(40012,"不合法的发送者"),
    INVALID_CORP_ID(40013,"不合法的corpid"),
    INVALID_ACCESS_TOKEN(40014,"不合法的access_token"),
    SENDER_NOT_IN_SESSION_(40015,"发送者不在会话中"),
    INVALID_SESSIONID(40016,"不合法的会话ID"),
    NOT_USER_IN_SENDER_CORPID(40017,"在会话中没有找到与发送者在同一企业的人"),
    RECURSION_NOT_PERMIT(40018,"不允许以递归方式查询部门用户列表"),
    JOIN_CORP_TOO_MORE(40019,"该手机号码对应的用户最多可以加入5个非认证企业"),
    CORP_PEOPLE_TOO_MORE(40020,"当前团队人数已经达到上限,用电脑登录钉钉企业管理后台，升级成为认证企业"),
    PHONENO_REGISTER(40021,"更换的号码已注册过钉钉，无法使用该号码"),
    PHONENO_DIFF(40022,"企业中的手机号码和登陆钉钉的手机号码不一致,暂时不支持修改用户信息,可以删除后重新添加"),
    DEPARTMENT_PEOPLE_TOO_MORE(40023,"部门人数达到上限"),
    PEOPLE_TOO_MORE(40024,"(安全校验不通过)保存失败，团队人数超限。请在手机钉钉绑定支付宝完成实名认证，或者申请企业认证，人数上限自动扩充。"),
    INVALID_DEPARTMENT_JSON(40025,"无效的部门JSONArray对象,合法格式需要用中括号括起来,且如果属于多部门,部门id需要用逗号分隔"),
    USER_EXIST(60107,"使用该手机登录钉钉的用户已经在企业中"),
    INVALID_OAUTH_CODE(40029,"不合法的oauth_code"),
    INVALID_USER_ID_LIST(40031,"不合法的UserID列表"),
    INVALID_USER_ID_LENGTH(40032,"不合法的UserID列表长度"),
    INVALID_REQUEST_WORD(40033,"不合法的请求字符，不能包含\\uxxx格式的字符"),
    INVALID_PARAM(40035,"不合法的参数"),
    INVALID_REQUEST_FORMAT(40038,"不合法的请求格式"),
    INVALID_URL_LENGTH(40039,"不合法的URL长度"),
    INVALID_URL_DOMAIN(40048,"url中包含不合法domain"),
    INVALID_AGENT_STRUCT(40055,"不合法的agent结构"),
    ILLEGAL_AGENTID(40056,"不合法的agentid"),
    INVALID_CALLBACK_URL(40057,"不合法的callbackurl"),
    SETTING_HEAD_FAILED(40061,"设置应用头像失败"),
    INVALID_APP_MODE(40062,"不合法的应用模式"),
    INVALID_TELEPHONE(40063,"不合法的分机号"),
    INVALID_ADDRESS(40064,"不合法的工作地址"),
    INVALID_REMARKER(40065,"不合法的备注"),
    INVALID_DEPARTMENT_LIST(40066,"不合法的部门列表"),
    INVALID_TITLE_LENGTH(40067,"标题长度不合法"),
    INVALID_OFFSET(40068,"不合法的偏移量"),
    INVALID_PAGE_SIZE(40069,"不合法的分页大小"),
    INVALID_ORDER_PARAM(40070,"不合法的排序参数"),
    OPENID_NOT_EXIST(40073,"不存在的openid"),
    OAUTH_CODE_NOT_EXIST(40077,"不存在的预授权码"),
    TEMP_OAUTH_CODE_NOTE_EXIST(40078,"不存在的临时授权码"),
    OAUTH_INFO_NOT_EXIST(40079,"不存在的授权信息"),
    INVALID_SUITE_SECRET(40080,"不合法的suitesecret"),
    INVALID_SUITE_TOKEN(40082,"不合法的suitetoken"),
    INVALID_SUITE_ID(40083,"不合法的suiteid"),
    INVALID_ACCESSTOKEN(40084,"不合法的永久授权码"),
    SUITE_TICKET_NOT_EXIST(40085,"不存在的suiteticket"),
    INVALID_APPID(40086,"不合法的第三方应用appid"),
    CREATE_OAUTH_CODE_FAILED(40087,"创建永久授权码失败"),
    INVALID_KEY_OR_SECRET(40088,"不合法的套件key或secret"),
    INVALID_CORPID_OR_CORPSECRET(40089,"不合法的corpid或corpsecret"),
    SUITE_NOT_EXIST(40090,"套件已经不存在"),
    CREATE_OAUTH_FAILED(40091,"用户授权码创建失败,需要用户重新授权"),
    LOST_ACCESS_TOKEN_PARAM(41001,"缺少access_token参数"),
    LOST_CORPID(41002,"缺少corpid参数"),
    LOST_REFRESH_TOKEN(41003,"缺少refresh_token参数"),
    LOST_SECRET(41004,"缺少secret参数"),
    LOST_MEDIA_DATA(41005,"缺少多媒体文件数据"),
    LOST_MEDIA_ID(41006,"缺少media_id参数"),
    INVALID_SSOCODE(41007,"无效的ssocode"),
    LOST_OAUTH(41008,"缺少oauth"),
    LOST_USERID(41009,"缺少UserID"),
    LOST_URL(41010,"缺少url"),
    LOST_AGENTID(41011,"缺少agentid"),
    LOST_APP_ICON(41012,"缺少应用头像mediaid"),
    LOST_APP_NAME(41013,"缺少应用名字"),
    LOST_APP_DESC(41014,"缺少应用描述"),
    LOST_CONENT(41015,"缺少Content"),
    LOST_TITLE(41016,"缺少标题"),
    LOST_SUITE_KEY(41021,"缺少suitekey"),
    LOST_SUITE_TOKEN(41022,"缺少suitetoken"),
    LOST_SUITE_TICKET(41023,"缺少suiteticket"),
    LOST_SUITE_SECRET(41024,"缺少suitesecret"),
    LOST_PERMANENT_CODE(41025,"缺少permanent_code"),
    LOST_TEMP_AUTH_CODE(41026,"缺少tmp_auth_code"),
    NEED_CORPID(41027,"需要授权企业的corpid参数"),
    FORBIDDEN_SEND_MSG_ALL(41028,"禁止给全员发送消息"),
    SEND_PEOPLE_TOO_MORE(41029,"超过消息接收者人数上限"),
    CORP_NO_PERMIT_SUITE(41030,"企业未对该套件授权"),
    AUTH_CORPID_NOT_EQUAL_PERMANENT_CODE(41031,"auth_corpid和permanent_code不匹配"),
    FORBIDDEN_SEND_MSG(41044,"禁止发送消息"),
    SEND_MSG_ALL_TOO_MORE(41045,"超过发送全员消息的次数上限"),
    SEND_MSG_ALL_MINUTE_TOO_MORE(41046,"超过发送全员消息的每分钟次数上限"),
    SEND_MSG_CORP_MINUTE_TOO_MORE(41047,"超过给该企业发消息的每分钟次数上限"),
    SEND_MSG_CORP_MINUTE_TOTAL_TOO_MORE(41048,"超过给企业发消息的每分钟次数总上限"),
    FORBIDDEN_MSG(41049,"包含违禁内容"),
    INVALID_ACTIVITY_CODE(41050,"无效的活动编码"),
    CHECK_ACTIVITY_FAILED(41051,"活动权益的校验失败"),
    ILLEGAL_TIME_PARAM(41100,"时间参数不合法"),
    DATA_CONTENT_TOO_LONG(41101,"数据内容过长"),
    PARAM_TOO_BIG(41102,"参数值过大"),
    ACCESS_TOKEN_TIMEOUT(42001,"access_token超时"),
    REFRESH_TOKEN_TIMEOUT(42002,"refresh_token超时"),
    OAUTH_CODE_TIMEOUT(42003,"oauth_code超时"),
    PRE_SALE_CODE_FAILED(42007,"预授权码失效"),
    TEMP_OAUTH_CODE_FAILED(42008,"临时授权码失效"),
    SUITE_TOKEN_FAILED(42009,"suitetoken失效"),
    NEED_GET(43001,"需要GET请求"),
    NEED_POST(43002,"需要POST请求"),
    NEED_HTTPS(43003,"需要HTTPS"),
    INVALID_HTTP_HEADER(43004,"无效的HTTP HEADER Content-Type"),
    CONTENT_TYPE_NEED_JSON(43005,"需要Content-Type为application/json;charset=UTF-8"),
    NEED_OAUTH(43007,"需要授权"),
    PARAM_NEED_MULTIPART(43008,"参数需要multipart类型"),
    POST_NEED_JSON(43009,"post参数需要json类型"),
    NEED_CALLBACK_MODE(43010,"需要处于回调模式"),
    NEED_CORP_OAUTH(43011,"需要企业授权"),
    MEDIA_FILE_NULL(44001,"多媒体文件为空"),
    POST_DATA_NULL(44002,"POST的数据包为空"),
    IMG_MSG_NULL(44003,"图文消息内容为空"),
    TEXT_MSG_NULL(44004,"文本消息内容为空"),
    MEDIA_FILE_TOO_BIG(45001,"多媒体文件大小超过限制"),
    TEXT_MSG_TOO_BIG(45002,"消息内容超过限制"),
    TITLE_TOO_BIG(45003,"标题字段超过限制"),
    DESC_TOO_BIG(45004,"描述字段超过限制"),
    LINK_TOO_BIG(45005,"链接字段超过限制"),
    IMG_LINK_TOO_BIG(45006,"图片链接字段超过限制"),
    VIDEO_PLAY_TIME_TOO_LONG(45007,"语音播放时间超过限制"),
    IMG_MSG_TOO_BIG(45008,"图文消息超过限制"),
    API_REQUEST_TOO_MANY(45009,"接口调用超过限制"),
    SYS_GROUP_NOT_MODIFY(45016,"系统分组，不允许修改"),
    GROUP_NAME_TOO_LONG(45017,"分组名字过长"),
    GROUP_NUM_TOO_MORE(45018,"分组数量超过上限"),
    ACCOUNT_NUM_TOO_MORE(45024,"账号数量超过上限"),
    MEDIA_DATA_NOT_EXIST(46001,"不存在媒体数据"),
    EMPLOYEE_NOT_EXIST(46004,"不存在的员工"),
    JSON_OR_XML_ERROR(47001,"解析JSON/XML内容错误"),
    API_FORBIDDEN(48002,"Api禁用"),
    INVALID_SUITE_TOEKN(48003,"suitetoken无效"),
    INVALID_OAUTH_RELATION(48004,"授权关系无效"),
    LOST_CHATID(49000,"缺少chatid"),
    WEI_APP_TOO_MANY(49001,"绑定的微应用超过个数限制"),
    ISV_ONLY_ONE_GROUP(49002,"一个群只能被一个ISV套件绑定一次"),
    OP_USER_MUST_OWNER(49003,"操作者必须为群主"),
    ADD_OR_DEL_USER_LIST_NOT_JOIN(49004,"添加成员列表和删除成员列表不能有交集"),
    GROUP_PEOPLE_TOO_MANY(49005,"群人数超过人数限制"),
    GROUP_LIST_NEED_OWNER(49006,"群成员列表必须包含群主"),
    GROUP_TOO_MANY(49007,"超过创建群的个数上限"),
    REDIRECT_URI_NOT_PERMIT(50001,"redirect_uri未授权"),
    USER_NOT_PERMIT(50002,"员工不在权限范围"),
    APP_STOP(50003,"应用已停用"),
    CORP_STOP(50005,"企业已禁用"),
    JUMP_DOMAIN_NOT_PERMIT(51000,"跳转的域名未授权"),
    JUMP_CORPID_NOT_PERMIT(51001,"跳转的corpid未授权"),
    JUMP_REQUEST_NOT_FROM_DINGTALK_CLIENT(51002,"跳转请求不是来自钉钉客户端"),
    JUMP_USER_NOT_FOUND(51003,"跳转找不到用户信息"),
    JUMP_CORP_NOT_FOUND(51004,"跳转找不到用户的企业信息"),
    JUMP_USER_NOT_CORP_ADMIN(51005,"跳转用户不是企业管理员"),
    JUMP_CODE_FAILED(51006,"跳转生成code失败"),
    JUMP_GET_USER_CORP_INFO_FAILED(51007,"跳转获取用户企业身份失败"),
    JUMP_URL_ENCODE_FAILED(51008,"跳转url解码失败"),
    JUMP_URL_INVALID(51009,"要跳转的地址不是标准url"),
    INVALID_CORPID(52010,"无效的corpid"),
    JSAPI_TICKET_READ_FAILED(52011,"jsapi ticket 读取失败"),
    JSAPI_CREATE_SIGNATURE_FAILED(52012,"jsapi 签名生成失败"),
    SIGNATURE_CHECK_FAILED(52013,"签名校验失败"),
    INVALID_URL_PARAM(52014,"无效的url参数"),
    INVALID_RANDOM_CHAR_PARAM(52015,"无效的随机字符串参数"),
    INVALID_SIGNATURE_PARAM(52016,"无效的签名参数"),
    INVALID_JSAPI_PARAM_LIST(52017,"无效的jsapi列表参数"),
    INVALID_TIMESTAMP(52018,"无效的时间戳"),
    INVALID_AGENTID(52019,"无效的agentid"),
    INVALID_DEPARTMENT_NAME(60001,"不合法的部门名称"),
    DEPARTMENT_DEEP_TOO_MANY(60002,"部门层级深度超过限制"),
    DEPARTMENT_NOT_EXIST(60003,"部门不存在"),
    PARENT_DEPARTMENT_NOT_EXIST(60004,"父亲部门不存在"),
    NOT_PERMIT_DEL_DEPARTMENT_HAS_USERS(60005,"不允许删除有成员的部门"),
    NO_PERMIT_DEL_DEPARTMENT_HAS_SUBDEPARTMENT(60006,"不允许删除有子部门的部门"),
    NOT_PERMIT_DEL_ROOT_DEPARTMENT(60007,"不允许删除根部门"),
    PARENT_DEPARTMENT_SUBDEPARTMENT_NAME_DUPLICATE(60008,"父部门下该部门名称已存在"),
    DEPARTMENT_NAME_ILLEGAL(60009,"部门名称含有非法字符"),
    DEPARTMENT_RELATION_LOOP(60010,"部门存在循环关系"),
    ADMIN_PERMIT_NOT_ENOUGH(60011,"管理员权限不足，（user/department/agent）无权限"),
    NO_PERMIT_DEL_DEFAULT_APP(60012,"不允许删除默认应用"),
    NO_PERMIT_CLOSE_APP(60013,"不允许关闭应用"),
    NO_PERMIT_OPEN_APP(60014,"不允许开启应用"),
    NO_PERMIT_MODIFY_APP_SEE_RANGE(60015,"不允许修改默认应用可见范围"),
    CORPID_EXIST(60016,"部门id已经存在"),
    NO_PERMIT_SETTING_CORP(60017,"不允许设置企业"),
    NO_PERMIT_UPDATE_ROOT_DEPARTMENT(60018,"不允许更新根部门"),
    QUERY_USER_BY_DEPARTMENT_FAILED(60019,"从部门查询人员失败"),
    REQUEST_IP_NOT_IN_WHITE_LIST(60020,"访问ip不在白名单之中"),
    CORP_SETTING_NOT_EXIST(60066,"企业的设置不存在"),
    DEPARTMENT_CORP_OWNER_NOT_EXIST(60067,"部门的企业群群主不存在"),
    DEPARTMENT_ADMIN_NOT_EXIST(60068,"部门的管理员不存在"),
    USERID_CORP_EXIST(60102,"UserID在公司中已存在"),
    ILLEGAL_PHONENO(60103,"手机号码不合法"),
    PHONENO_CORP_EXIST(60104,"手机号码在公司中已存在"),
    ILLEGAL_EMAIL(60105,"邮箱不合法"),
    CORP_EMAIL_EXIST(60106,"邮箱已存在"),
    CORP_PHONENO_EXIST(60107,"使用该手机登录钉钉的用户已经在企业中"),
    DEPARMENT_NUM_TOO_MORE(60110,"部门个数超出限制"),
    USERID_NOT_EXIST(60111,"UserID不存在"),
    ILLEGAL_USER_NAME(60112,"用户name不合法"),
    IDENTIFY_INFO_NOT_NULL(60113,"身份认证信息（手机/邮箱）不能同时为空"),
    ILLEGAL_SEX(60114,"性别不合法"),
    USER_INVALID_INVITE_CODE(60118,"用户无有效邀请字段（邮箱，手机号）"),
    ILLEGAL_POSITION(60119,"不合法的position"),
    USER_FORBIDDEN(60120,"用户已禁用"),
    USER_NOT_FOUND(60121,"找不到该用户"),
    ILLEGAL_EXTATTR(60122,"不合法的extattr"),
    ILLEGAL_JOB_NUM(60123,"不合法的jobnumber"),
    USER_NOT_IN_GROUP(60124,"用户不在此群中"),
    CRM_CONFIG_INFO_CREATE_FAILED(60125,"CRM配置信息创建失败"),
    CRM_CONFIG_INFO_UPDATE_FAILED(60126,"CRM配置信息更新失败"),
    CRM_USER_CONFIG_INFO_DEL_FAILED(60127,"CRM人员配置信息删除失败"),
    CORP_NOT_EXIST_OR_RELEASE(70001,"企业不存在或者已经被解散"),
    GET_SUITE_APP_FAILED(70002,"获取套件下的微应用失败"),
    AGENTID_APP_NOT_EXIST(70003,"agentid对应微应用不存在"),
    CORP_AGENTID_APP_NOT_EXIST(70004,"企业下没有对应该agentid的微应用"),
    ISV_SUITE_ACT_FAILED(70005,"ISV激活套件失败"),
    CALLBACK_ADDRESS_EXIST(71006,"回调地址已经存在"),
    CALLBACK_ADDRESS_NOT_EXIST(71007,"回调地址已不存在"),
    CALLBACK_TAG_NOT_IN_LIST(71008,"回调call_back_tag必须在指定的call_back_tag列表中"),
    RETURN_NOT_SUCCESS(71009,"返回文本非success"),
    INVALID_POST_DATA_OR_PARAM_FORMAT_(71010,"POST的JSON数据不包含所需要的参数字段或包含的参数格式非法"),
    ILLEGAL_URL_PARAM(71011,"传入的url参数不是合法的url格式"),
    URL_ADDRESS_EXCEPTION(71012,"url地址访问异常,错误原因为:%s"),
    INVALID_DOMAIN_OR_IP_ACCEPT_CALLBACK(71013,"此域名或IP不能注册或者接收回调事件"),
    GET_DINGTALK_SPACE_FAILED(72001,"获取钉盘空间失败"),
    OAUTH_DINGTALK_SPACE_AUTH_FAILED(72002,"授权钉盘空间访问权限失败"),
    JSSDK_DOMAIN_IPC_NOT_PASS(80001,"可信域名没有IPC备案，后续将不能在该域名下正常使用jssdk"),
    USER_RELATION_NOT_EXIST(81001,"两个用户没有任何关系，请先相互成为好友"),
    USER_REFUSE_MSG(81002,"用户拒收消息"),
    MANAGER_CALENDAR_OP_FAILED(88005,"管理日历个人日历操作失败"),
    MANAGER_CALENDAR_EXPORT_TASK_FAILED(89001,"管理日历启动导出任务失败"),
    MANAGER_CALENDAR_WRITE_DATA_FAILED(89011,"管理日历写入数据失败"),
    MANAGER_CALENDAR_UPDATE_DATE_FAILED(89012,"管理日历更新数据失败"),
    SERVER_IP_FORBIDDEN(90001,"您的服务器调用钉钉开放平台所有接口的请求都被暂时禁用了"),
    SERVER_IP_CUR_API_FORBIDDEN(90002,"您的服务器调用钉钉开放平台当前接口的所有请求都被暂时禁用了"),
    SERVER_IP_FORBIDDEN_ONLY_SELF_VALID(90003,"您的企业调用钉钉开放平台所有接口的请求都被暂时禁用了,仅对企业自己的Accesstoken有效"),
    CORPID_CORPSECRET_FORBIDDEN_ONLY_SELF_VALID(90004,"您当前使用的CorpId及CorpSecret被暂时禁用了,仅对企业自己的Accesstoken有效"),
    REQUEST_API_TOO_MANY_ONLY_SELF_VALID(90005,"您的企业调用当前接口次数过多,请求被暂时禁用了,仅对企业自己的Accesstoken有效"),
    CORPID_SECRET_REQ_TOO_MANY_ONLY_SELF_VALID(90006,"您当前使用的CorpId及CorpSecret调用当前接口次数过多,请求被暂时禁用了,仅对企业自己的Accesstoken有效"),
    REQ_TOO_MANY_ONLY_ISV_VALID(90007,"您当前要调用的企业的接口次数过多,对该企业的所有请求都被暂时禁用了,仅对企业授权给ISV的Accesstoken有效"),
    CUR_CORP_REQ_TOO_MANY_ONLY_ISV_VALID(90008,"您当前要调用的企业的当前接口次数过多,对此企业下该接口的所有请求都被暂时禁用了,仅对企业授权给ISV的Accesstoken有效"),
    REQ_CORP_TOO_MANY_ONLY_ISV_VALID(90009,"您调用企业接口超过了限制,对所有企业的所有接口的请求都被暂时禁用了,仅对企业授权给ISV的Accesstoken有效"),
    REQ_CUR_API_TOO_MANY_ONLY_ISV_VALID(90010,"您调用企业当前接口超过了限制,对所有企业的该接口的请求都被暂时禁用了,仅对企业授权给ISV的Accesstoken有效"),
    SUITE_REQ_TOO_MANY_ONLY_ISV_VALID(90011,"您的套件调用企业接口超过了限制,该套件的所有请求都被暂时禁用了,仅对企业授权给ISV的Accesstoken有效"),
    SUITE_REQ_CUR_CORP_TOO_MANY_ONLY_ISV_VALID(90012,"您的套件调用企业当前接口超过了限制,该套件对此接口的所有请求都被暂时禁用了,仅对企业授权给ISV的Accesstoken有效"),
    SUITE_REQ_CUR_CORP_TOO_MANY_ALL_ONLY_ISV_VALID(90013,"您的套件调用当前企业的接口超过了限制,该套件对此企业的所有请求都被暂时禁用了,仅对企业授权给ISV的Accesstoken有效"),
    SUITE_REQ_TOO_MANY_ALL_ONLY_ISV_VALID(90014,"您的套件调用企业当前接口超过了限制,该套件对此企业该接口的所有请求都被暂时禁用了,仅对企业授权给ISV的Accesstoken有效"),
    ILLEGAL_ENCODE_MW_TEXT(900001,"加密明文文本非法"),
    ILLEGAL_ENCODE_TIMESTAMP_PARAM(900002,"加密时间戳参数非法"),
    ILLEGAL_ENCODE_RANDOM_CHAR_PARAM(900003,"加密随机字符串参数非法"),
    ILLEGAL_AESKEY(900004,"不合法的aeskey"),
    SIGNATURE_NOT_EQUAL(900005,"签名不匹配"),
    CAL_SIGNATURE_ERROR(900006,"计算签名错误"),
    ENCODE_TEXT_ERROR(900007,"计算加密文字错误"),
    DECODE_TEXT_ERROR(900008,"计算解密文字错误"),
    DECODE_TEXT_LENGTH_NOT_EQUAL(900009,"计算解密文字长度不匹配"),
    DECODE_CORPID_NOT_EQUAL(900010,"计算解密文字corpid不匹配"),
    CUST_EXIST(420001,"客户不存在"),
    CUST_QUERY_FAILED(420002,"客户查询失败"),
    CONTACT_NOT_EXIST(420003,"联系人不存在"),
    CONTACT_QUERY_FAILED(420004,"联系人查询失败"),
    CUST_DEL_FAILED(420005,"客户删除失败"),
    CONTACT_DEL_FAILED(420006,"联系人删除失败"),
    FOLLOWING_USER_BING_FAILED(420007,"跟进人绑定失败"),
    CUST_ID_ILLEGAL(420008,"客户id非法"),
    FOLLOWING_UID_ILLEGAL(420009,"跟进人id非法"),
    CUST_CONTACT_ID_ILLEGAL(4200010,"客户联系人id非法"),
    CUST_DESC_NOT_EXIST(4200011,"客户描述表单不存在"),
    CUST_DESC_QUERY_FAILED(4200012,"客户描述表单查询失败"),
    CUST_CONTACT_NOT_EXIST(4200013,"联系人描述表单不存在"),
    CUST_CONTACT_QUERY_FAILED(4200014,"联系人描述表单查询失败"),
    CUST_DESC_FORM_FORMAT_ERROR(4200015,"客户描述表单格式校验错误"),
    CUST_DESC_FORM_LOST_FILED(4200016,"客户描述表单格缺少固定字段"),
    CUST_CONTACT_FORM_FORMAT_ERROR(4200017,"客户联系人描述表单格式校验错误"),
    CUST_CONTACT_FORM_LOST_FILED(4200018,"客户联系人描述表单格缺少固定字段"),
    CUST_DESC_DATA_FORMAT_ERROR(4200019,"客户描述表单数据格式校验错误"),
    CUST_DESC_DATA_LOST_FIELD(4200020,"客户描述表单数据缺少固定字段"),
    CUST_CONTACT_DATA_FORMATE_ERROR(4200021,"客户联系人描述表单数据格式校验错误"),
    CUST_CONTACT_DATA_LOST_FIELD(4200022,"客户联系人描述表单数据缺少固定字段"),
    ENCODE_FAILED(41042,"加密失败"),
    DECODE_FAILED(41043,"解密失败"),
    TELEPHONE_EXIST(40100,"分机号已经存在"),
    EMAIL_EXIST(40101,"邮箱已经存在"),
    CORP_EMPLOYEE_NOT_PERMIT(50002,"企业员工不在授权范围"),
    CORP_DEPARTMENT_NOT_PERMIT(50004,"企业部门不在授权范围"),
    OTHER_ERROR(99999, "其他错误");

    /**
     * 结果码
     */
    Integer code;

    /**
     * 结果描述
     */
    String description;

    /**
     * 返回结果枚举构造方法
     *
     * @param code        结果码
     * @param description 结果描述
     */
    ResultType(Integer code, String description) {
        this.code = code;
        this.description = description;
    }

    /**
     * 通过code得到返回结果对象
     *
     * @param code 结果码
     * @return 结果枚举对象
     */
    public static ResultType get(String code) {
        ResultType[] list = values();
        for (ResultType resultType : list) {
            if (code.equals(resultType.getCode().toString())) {
                return resultType;
            }
        }
        return null;
    }

    /**
     * 获得结果码
     *
     * @return 结果码
     */
    public Integer getCode() {
        return code;
    }

    /**
     * 获得结果描述
     *
     * @return 结果描述
     */
    public String getDescription() {
        return description;
    }

    @Override
    public String toString() {
        return "ResultType{" +
                "code=" + code +
                ", description='" + description + '\'' +
                '}';
    }
}